### ISSUE TITLE
Support vector index syntax

### ISSUE THREAD

**Issue by korsvanloon** [neo4j/cypher-language-support#193]
I copied and paste an example from a GraphAcademy tutorial and I got some syntax highlighting issues.

It seems the vector index syntax is not yet supported:

<img width="356" alt="Scherm­afbeelding 2024-03-29 om 09 08 03" src="https://github.com/neo4j/cypher-language-support/assets/3833962/92e1ed3d-fb57-4148-8f29-e34b979892c7">

**Comment by OskarDamkjaer** [comment]
Hi @korsvanloon! We updated the grammar to support vector index syntax [last week](https://github.com/neo4j/cypher-language-support/pull/179/files), but we've not set up automatic releases for vscode yet, so it's not been published. Thanks for making us aware of the issue, I'll close the issue once we've published the newer version 😄

**Comment by ncordon** [comment]
Hey @korsvanloon! The new version of the VSCode plugin has been made available at the Marketplace. I've checked it supports the vector indexes, you just need to update.
