### ISSUE TITLE
Complex statement with escaped characters breaking syntax highlighting

### ISSUE THREAD

**Issue by mcclown** [neo4j/cypher-language-support#236]
![image](https://github.com/neo4j/cypher-language-support/assets/1173840/227d2710-4fe6-45ac-8c1c-7fb97059ce36)

The complex expression that is breaking the highlighting is 

`WITH nerlQ, REPLACE(REPLACE(REPLACE(REPLACE(apoc.text.replace(nerlQ.content, "[\"(){}!?*~:+-^]", ""), "[", ""), "]", ""), "\\", ""), "/", "") as contentClean`

VSCode version:

Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Plugin Version: v1.2.1

**Comment by ncordon** [comment]
Thanks a lot for reporting 😄 ! I'll look into it

**Comment by ncordon** [comment]
I could reproduce with the 1.2.1 version of the plugin, but the 1.2.2 seems to have solved this:

<img width="1542" src="https://github.com/user-attachments/assets/9256c6c0-3bf3-4e3a-bd24-a331385eda20">
