### ISSUE TITLE
VS Code Extension does not pull information from Aura DB

### ISSUE THREAD

**Issue by anthony-b-dev** [neo4j/cypher-language-support#238]
Hello, new to Neo4j and I was trying to get set up with the VS Code extension for some highlighting and autocompletion. It looks like the highlighting works decently, but it doesn't seem to pull any information from the database so I'm still typing everything out manually. I don't even have the option to specify extension settings in `.vscode/settings.json ` to potentially link it to my database.

I have a free AuraDB instance that I'm trying to mess around with.

I can't seem to figure out what I'm missing here?

**Comment by ncordon** [comment]
I'll close this due to inactivity. As described, the plugin does indeed work with Aura DBs, let us know if you have other questions we could help with.
